github/workflows: Fix cargo audit installation
During CI, attempting to install `cargo-audit` causes the
following error:
```
error: failed to compile `cargo-audit v0.22.1` ...
...
Caused by:
  rustc 1.88.0 is not supported by the following package:
    smol_str@0.3.6 requires rustc 1.89
  Try re-running `cargo install` with `--locked`
```

Update the workflow, as suggested by the error message,
including the `--locked` flag.

Signed-off-by: Nicola Ramacciotti <niko.ramak@gmail.com>