boot: bootimg/elf: page-align kernel ELF size
Code in multiple places may assume that the virtual size of the SVSM
kernel is page-aligned. This assumption is made when computing the
base of the kernel heap, which is placed right after the kernel in
the virtual address space. If the end of the kernel ELF image is not
page-aligned, the heap base won't be either, causing issues when mapping
it:

  [Stage2] COCONUT Secure Virtual Machine Service Module Version 2026.02-devel-22-gdb719c17+
  [Stage2] SVSM memory region: [0x0000008000000000-0x0000008001000000]
  [Stage2] ERROR: Panic! COCONUT-SVSM Version: 2026.02-devel-22-gdb719c17+
  [Stage2] ERROR: Info: panicked at boot/bootimg/src/page_tables.rs:182:9:
  assertion failed: is_page_aligned(vaddr)

Fix this by page-aligning upwards the size of the kernel ELF. While we
are at it, assert that any added space between the end of the ELF and
the beginning of the heap is also a multiple of the page size, to catch
potential similar issues.

Signed-off-by: Carlos López <clopez@suse.de>