verification/verus_macro_stub: remove unused extern crate
clippy returns this warning:

`
error: unused extern crate
 --> verification/verus_macro_stub/src/lib.rs:7:1
  |
7 | extern crate proc_macro;
  | ^^^^^^^^^^^^^^^^^^^^^^^^ help: remove it
`

Fix it by removing the line.

Signed-off-by: Luigi Leonardi <leonardi@redhat.com>