platform/snp: enable alternate injection only if requested
The current logic for enabling alternate injection is broken, as it
will enable it always. This is causing a crash during boot when
running under a hypervisor that does not support the feature:

    [SVSM] ERROR: Panic: CPU[0] panicked at kernel/src/svsm.rs:449:36:
    Failed to setup guest VMSA/CAA: Ghcb(VmgexitError(2, 6))
    [SVSM] ---BACKTRACE---:
    [SVSM]   [0xffffff8000128445]
    [SVSM]   Invalid frame
    [SVSM] ---END---

Fix this by checking upfront if the feature was requested.

Fixes: 978aef5a9d75 ("protocols/apic: update the registration-based APIC protocol")
Signed-off-by: Carlos López <carlos.lopez@suse.com>