Highlight build issue with std and no_std in the same workspace
PLEASE DON'T MERGE!

This commit is just to highlight the problem I am having. I have minimized
the changes to only discuss the problem.

In this case I added a dependency (rdrand) that supports std or no_std with
the (std) feature enabled by default. Here I am disabling it for use in the
kernel without std.

Dependencies

- kernel
  -> rdrand (default-features = false, so "std" feature disabled)
     -> rand_core (default-features = false, so "std" feature disabled)
        -> getrandom (default-features = false, so it should be disabled)
- igvmmeasure
  -> p384 (default-features = true)
     -> elliptic-curve
        -> rand_core
           -> getrandom

But when building `svsm`, cargo seems to use an interesention of the features
used in the workspace, as it goes to compile `getrandom` which should be
disabled, more expecting std.

```
$ make
cargo build --manifest-path kernel/Cargo.toml  --no-default-features --bin stage2
   Compiling svsm v0.1.0 (/home/stefano/repos/coconut/svsm-review/kernel)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.00s
objcopy -O binary "target/x86_64-unknown-none/debug/stage2" bin/stage2.bin
touch bin/svsm-fs.bin
cargo build  --features "default" --bin svsm
   Compiling getrandom v0.2.12
   Compiling svsm v0.1.0 (/home/stefano/repos/coconut/svsm-review/kernel)
   Compiling zerocopy v0.7.32
   Compiling zerocopy v0.6.6
   Compiling crypto-common v0.1.6
   Compiling inout v0.1.3
error[E0463]: can't find crate for `std`
 --> /home/stefano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.12/src/error_impls.rs:2:1
  |
2 | extern crate std;
  | ^^^^^^^^^^^^^^^^^ can't find crate
  |
  = note: the `x86_64-unknown-none` target may not support the standard library

error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> /home/stefano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.12/src/lib.rs:296:9
    |
296 | /         compile_error!("target is not supported, for more information see: \
297 | |                         https://docs.rs/getrandom/#unsupported-targets");
    | |________________________________________________________________________^

   Compiling universal-hash v0.5.1
   Compiling aead v0.5.2
error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /home/stefano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.12/src/lib.rs:347:9
    |
347 |         imp::getrandom_inner(dest)?;
    |         ^^^ use of undeclared crate or module `imp`

Some errors have detailed explanations: E0433, E0463.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `getrandom` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:118: bin/svsm-kernel.elf] Error 101
```