libtcgtpm: set `-Wno-error=unused-variable` in TPM CFLAGS
The next commit switches to TCG TPM, but there is a problem when the
`FILE_BACKED_NV` macro is set to `NO`. It produces the following compile
error because a variable is not used:

    Platform/src/NVMem.c: In function ‘_plat__NVDisable’:
    Platform/src/NVMem.c:185:9: error: unused variable ‘delete’ [-Werror=unused-variable]
      185 |     int delete = ((intptr_t)platParameter != 0)
          |         ^~~~~~
    cc1: all warnings being treated as errors
    make[2]: *** [Makefile:2674: Platform/src/libplatform_a-NVMem.o] Error 1

This commit can be reverted when the following PR will be merged:
https://github.com/TrustedComputingGroup/TPM/pull/7

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>