INSTALL.md: fix unit tests instructions
The OVMF variable is now unnecessary since the firmware will eventually
be embedded in the IGVM file.

Let's also add a note to clarify that we need to install the target
`x86_64-unknown-none` for the nightly toolchain to avoid the following
error:

    $ QEMU=/path/to/qemu-system-x86_64 make test-in-svsm
    ...
    LINK_TEST=1 cargo +nightly test  -p svsm --config 'target.x86_64-unknown-none.runner=["sh", "-c", "cp $0 ../target/x86_64-unknown-none/debug/svsm-test"]'
    error[E0463]: can't find crate for `core`
      |
      = note: the `x86_64-unknown-none` target may not be installed
      = help: consider downloading the target with `rustup target add x86_64-unknown-none`
      = help: consider building the standard library from source with `cargo build -Zbuild-std`

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>