stage2: rename push_regs to push_regs_stage2
When building the fuzzing harnesses, rustc would complain that
`push_regs` was defined twice. Fix this by renaming push_regs in
stage 2 to push_regs_stage2.

error: symbol 'push_regs' is already defined
    |
note: instantiated into assembly here
   --> <inline asm>:105:5
    |
105 |     push_regs:
    |     ^

error: could not compile `svsm` (lib) due to previous error

Signed-off-by: Carlos López <carlos.lopez@suse.com>