kernel: fix `borrow_as_ptr` lint for Rust 1.88.0
Running `cargo clippy` with the Rust 1.88.0 toolchain produces warnings
like:

    error: implicit borrow as raw pointer
       --> kernel/src/cpu/gdt.rs:138:26
        |
    138 |                  in(reg) &gdt_desc,
        |                          ^^^^^^^^^
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#borrow_as_ptr
    help: use a raw pointer instead
        |
    138 |                  in(reg) &raw const gdt_desc,
        |                           +++++++++

Use `&raw const`/`&raw mut` instead of implicit borrow as raw pointer
as suggested to fix them.

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>