kernel/vtpm: fix `manual_dangling_ptr` lint for Rust 1.88.0
Running `cargo clippy` with the Rust 1.88.0 toolchain produces the
following warning:

    error: manual creation of a dangling pointer
       --> kernel/src/vtpm/tcgtpm/mod.rs:199:39
        |
    199 |             unsafe { _plat__NVDisable(1 as *mut c_void, 0) };
        |                                       ^^^^^^^^^^^^^^^^
        |                                       help: use: `core::ptr::dangling_mut::<c_void>()`
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_dangling_ptr

The suggested `core::ptr::dangling_mut()` would produce the same value
(since `c_void` has alignment 1), but it misrepresents the intent: the
value `1` is deliberately chosen as a flag value passed to the FFI
`_plat__NVDisable()` function, not as a dangling pointer. Use
`core::ptr::without_provenance_mut(1)` instead to make this intent
explicit while satisfying the lint.

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>