cpu/percpu: be consistent about mutable references
VmsaRef::vmsa() and PerCpu::guest_vmsa() return a &mut VMSA, but take
an immutable reference to self, which confues clippy and might even
produce strange behavior if the compiler decides to use this to
optimize. We currently get away with this due to casting a VirtAddr
to a mutable pointer. Be consistent about mutability by changing the
signature of these methods to take &mut self.

This fixes the following clippy warnings:

error: mutable borrow from immutable input(s)
   --> src/cpu/percpu.rs:101:27
    |
101 |     pub fn vmsa(&self) -> &mut VMSA {
    |                           ^^^^^^^^^
    |
note: immutable borrow here
   --> src/cpu/percpu.rs:101:17
    |
101 |     pub fn vmsa(&self) -> &mut VMSA {
    |                 ^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mut_from_ref
    = note: `#[deny(clippy::mut_from_ref)]` on by default

error: mutable borrow from immutable input(s)
   --> src/cpu/percpu.rs:421:33
    |
421 |     pub fn guest_vmsa(&self) -> &mut VMSA {
    |                                 ^^^^^^^^^
    |
note: immutable borrow here
   --> src/cpu/percpu.rs:421:23
    |
421 |     pub fn guest_vmsa(&self) -> &mut VMSA {
    |                       ^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mut_from_ref

Signed-off-by: Carlos López <carlos.lopez@suse.com>