kernel/vsock: fix flaky double_connect test
The test_virtio_vsock_double_connect test was flaky because it relied on
timing for the second connect() to fail, assuming the server had already
closed its listening socket by the time the guest attempted the second
connection:

    test vsock::stream::tests::test_virtio_vsock_double_connect ...
    ERROR: Panic on CPU[3]! COCONUT-SVSM Version: 2026.06-devel-120-g54cd9681
    ERROR: Info: panicked at kernel/src/vsock/stream.rs:184:14:
    The second connection operation was expected to fail, but it succeeded.: VsockStream { local_port: 1025, remote_port: 12345, remote_cid: 2 }
    ---BACKTRACE---:
      [ffffff8000092792] core::panicking::panic_bounds_check+0x0
      [ffffff8000042d24] svsm::vsock::stream::tests::test_virtio_vsock_double_connect+0xf4
      [ffffff800001d8f9] <svsm::vsock::stream::tests::test_virtio_vsock_double_connect::{closure#0} as core::ops::function::FnOnce<()>>::call_once+0x9
      [ffffff8000011f66] svsm::testing::svsm_kernel_test_runner+0xc6
      [ffffff8000052109] svsm::svsm_bin::test_in_svsm_task+0x19
      [ffffff80000953d4] @ thread_entry_asm+0x18
    ---END---

Make this deterministic by reading the "hello_world" message from the
server before attempting the second connect. Since the new python vsock
server closes the listening socket before sending the message, a successful
read guarantees that no further connections can be accepted.

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>