cpu/vmsa: take mutable reference instead of raw pointer in init_guest_vmsa()
The only caller already has a mutable reference, so there is no need
to take a raw pointer.

Fixes the following clippy warning:

error: this public function might dereference a raw pointer but is not marked `unsafe`
   --> src/cpu/vmsa.rs:110:22
    |
110 |     let v = unsafe { vmsa.as_mut().unwrap() };
    |                      ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref
    = note: `#[deny(clippy::not_unsafe_ptr_arg_deref)]` on by default

Signed-off-by: Carlos López <carlos.lopez@suse.com>