fs/ramfs: implement Send for RamDirectory
RamDirectory has an internal lock protecting access to the directory
entries, so it can safely implement Send. This fixes the following
clippy warning:

error: usage of `Arc<T>` where `T` is not `Send` or `Sync`
   --> src/fs/filesystem.rs:135:20
    |
135 |     let root_dir = Arc::new(RamDirectory::new());
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider using `Rc<T>` instead or wrapping `T` in a std::sync type like `Mutex<T>`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync
    = note: `#[deny(clippy::arc_with_non_send_sync)]` on by default

Signed-off-by: Carlos López <carlos.lopez@suse.com>