Revert "github/workflows: cargo audit"
Reverts coconut-svsm/svsm#1004

This workflow is failing with tip-of-tree sources, giving the following error:
```
      Adding smol_str v0.3.6 (requires Rust 1.89)
error: failed to compile `cargo-audit v0.22.1`, intermediate artifacts can be found at `/tmp/cargo-installMrndJy`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.88.0 is not supported by the following package:
    smol_str@0.3.6 requires rustc 1.89
  Try re-running `cargo install` with `--locked`
```

Updating our Rust version is not trivial so we should disable this workflow until we can either update the toolchain or change the workflow to avoid the error.

Signed-off-by: Jon Lange <jlange@microsoft.com>