error: avoid `SvsmReqError` outside of SVSM-specific paths
The `SvsmReqError` type is defined based on the SVSM protocol, and its
use should only be a part of code paths that specifically support the
SVSM protocol.  Common code paths that provide general services should
use the system-wide error type `SvsmError`.

Signed-off-by: Jon Lange <jlange@microsoft.com>